branch-defaults:
  multi-docker:
    environment: MultiDocker-env
global:
  application_name: multi-docker
  default_ec2_keyname: mykey
  default_platform: Multi-container Docker
  default_region: ap-northeast-1
  sc: git
